# -*- coding: utf-8 -*-
"""conteo_combinatorio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i8RSyeJmIWARBDJay99j4hPDRhz_D4VB

# <font face="Times New Roman"> Problemas de Conteo Combinatorio
<font face="Times New Roman" size="4">
Trabajo del bono programable que incorpora codigo prueba, calculadora y menu final de los casos de conteo combinatorio distribución de objetos en cajas e inclusión-exclusión para conteos con restricciones. Incluye descripción matemática, fórmula, algoritmo, código, pruebas y comentarios de eficiencia.
</font>

---
"""

import math
from itertools import permutations
from collections import Counter

"""---
# <font face="Times New Roman"> Problema 1:  Coeficientes Multinomiales y Palabras con Letras Repetidas

## <font face="Times New Roman"> Descripción matemática

Dado un conjunto de $n$ objetos donde hay $k$ tipos distintos con $n_1, n_2, \ldots, n_k$ objetos de cada tipo
(con $n_1 + n_2 + \cdots + n_k = n$), ¿de cuántas formas distintas se pueden ordenar?

El problema surge porque los objetos dentro de un mismo grupo son **indistinguibles** entre sí.
Por ejemplo, la palabra **BANANA** tiene 6 letras, pero intercambiar las tres A entre sí no produce
una palabra nueva. Si no se tomara eso en cuenta, contaríamos $6! = 720$ ordenamientos,
pero muchos de ellos son idénticos.

**Ejemplos de aplicación:**
- ¿Cuántas palabras distintas se forman con las letras de BANANA?
- ¿Cuántas cadenas distintas tienen 4 letras A, 3 letras B y 2 letras C?

## <font face="Times New Roman" size="4"> Fórmula usada

El **coeficiente multinomial** divide el total de permutaciones por las permutaciones indistinguibles
dentro de cada grupo:

$$\binom{n}{n_1, n_2, \ldots, n_k} = \frac{n!}{n_1! \cdot n_2! \cdots n_k!}$$

donde $n = n_1 + n_2 + \cdots + n_k$.

**Explicación**
El numerador $n!$ cuenta todas las formas de ordenar $n$ objetos como si fueran distintos.
El denominador cancela los reordenamientos internos de cada grupo que producen el mismo resultado.
Para BANANA: $n=6$, $n_B=1$, $n_A=3$, $n_N=2$:

$$\frac{6!}{1! \cdot 3! \cdot 2!} = \frac{720}{1 \cdot 6 \cdot 2} = 60$$

## <font face="Times New Roman"> Explicación del algoritmo

El algoritmo recibe una lista de frecuencias $[n_1, n_2, \ldots, n_k]$ y:

1. **Valida** que todos los valores sean enteros no negativos.
2. **Calcula** $n = \sum n_i$.
3. **Computa** $n!$ en el numerador.
4. **Computa** el producto $n_1! \cdot n_2! \cdots n_k!$ en el denominador.
5. **Retorna** la división entera exacta.

Cuando la entrada es una palabra, primero se extraen las frecuencias de cada letra con un contador.

**Complejidad:** $O(n)$ en tiempo (un recorrido para sumar, uno para cada factorial).

## <font face="Times New Roman"> Código
"""

def multinomial(counts: list[int]) -> int:
    """
    Calcula el coeficiente multinomial dado una lista de frecuencias.

    Parametros:
      counts: lista de enteros no negativos [n1, n2, ..., nk]

    Retorna:
      n! / (n1! * n2! * ... * nk!)  como entero exacto

    Lanza ValueError si algun conteo es negativo o no es entero.
    """
    if not counts:
        return 1  # caso vacio: 1 forma de ordenar 0 objetos
    if any(not isinstance(c, int) or c < 0 for c in counts):
        raise ValueError("Cada n_i debe ser un entero no negativo.")

    n = sum(counts)
    if n == 0:
        return 1

    numerador = math.factorial(n)
    denominador = 1
    for c in counts:
        denominador *= math.factorial(c)

    return numerador // denominador


def multinomial_desde_palabra(palabra: str) -> tuple[int, dict]:
    """
    Calcula el coeficiente multinomial a partir de una palabra.

    Parametros:
      palabra: cadena de caracteres (ej: "BANANA")

    Retorna:
      (resultado, frecuencias)
    """
    palabra = palabra.upper()
    if not palabra:
        raise ValueError("La palabra no puede estar vacia.")

    freq = Counter(palabra)
    counts = list(freq.values())
    resultado = multinomial(counts)
    return resultado, dict(freq)


def generar_palabras_distintas(palabra: str) -> list[str]:
    """
    genera todas las palabras distintas que se pueden formar
    con las letras de 'palabra'. no olvidar len <= 8
    """
    if len(palabra) > 8:
        raise ValueError(f"Palabra demasiado larga ({len(palabra)} letras). maximo 8 para generacion.")
    return sorted(set(''.join(p) for p in permutations(palabra.upper())))

"""## <font face="Times New Roman"> Pruebas"""

def pruebas_multinomial():
    print("=" * 60)
    print("PRUEBAS — Problema 1: Coeficiente Multinomial")
    print("=" * 60)

    casos = [
        # (descripción, entrada, esperado, es_palabra)
        ("BANANA",               "BANANA",       60,      True),
        ("AABB",                 "AABB",           6,      True),
        ("MISSISSIPPI",          "MISSISSIPPI", 34650,    True),
        ("Una sola letra A",     "A",              1,      True),
        ("Sin repetición ABCDE", "ABCDE",        120,      True),
        ("[4,3,2] → 4A+3B+2C",  [4, 3, 2],     1260,    False),
        ("[2,2,2]",              [2, 2, 2],       90,    False),
    ]

    aprobados = 0
    for desc, entrada, esperado, es_palabra in casos:
        try:
            if es_palabra:
                resultado, freq = multinomial_desde_palabra(entrada)
                detalle = f"freq={freq}"
            else:
                resultado = multinomial(entrada)
                detalle = f"counts={entrada}"
            ok = resultado == esperado
            estado = "bueno" if ok else "falla"
            if ok: aprobados += 1
            print(f"  {estado}  {desc:30s}  {detalle}  →  {resultado}  (esperado {esperado})")
        except Exception as e:
            print(f"  error  {desc}: {e}")

    print(f"\n  Resultado: {aprobados}/{len(casos)} pruebas aprobadas\n")


pruebas_multinomial()

"""### <font face="Times New Roman"> Validación de casos especiales"""

def casos_especiales_multinomial():
    print(" TEST DE CASOS RAROS ")

    # ¿vacío da 1?
    vacio = multinomial([])
    print(f"Vacio: {vacio} (esperado: 1)")

    # con un solo elemento
    uno = multinomial([1])
    print(f"Un elemento [1]: {uno}")

    # todos iguales (ej: 5!/5! tendría que dar 1)
    iguales = multinomial([5])
    print(f"Iguales [5]: {iguales}")

    # el cero no deberia cambiar el resultado
    con_cero = multinomial([4, 0, 2])
    sin_cero = multinomial([4, 2])
    print(f"¿[4,0,2] es igual a [4,2]?: {con_cero == sin_cero} ({con_cero} vs {sin_cero})")

    # numeros mas grandes
    grande = multinomial([10, 10, 10, 10])
    print(f"Numero grande [10,10,10,10]: {grande:,}")

    # romperlo a proposito con negativos
    try:
        multinomial([-1, 2])
        print("no salto error con negativos")
    except ValueError as e:
        print(f"Negativos bien (se rompio bien): {e}")

    # romperlo con floats
    try:
        multinomial([2.5, 3])  # type: ignore
        print("ALERTA: no salto error con floats")
    except (ValueError, TypeError):
        print("Floats ok (salio error esperado)")


casos_especiales_multinomial()

"""## <font face="Times New Roman">  Calculadora interactiva"""

def interfaz_multinomial(modo):

    "Interfaz interactiva para el usuario"

    if modo == "1":
        palabra = input(" Palabra: ").strip()
        resultado, freq = multinomial_desde_palabra(palabra)
        print(f"\n Frecuencias: {freq}")
        print(f" Palabras distintas: {resultado}")

        if len(palabra) <= 8:
            ver = input(" Generar todas las palabras si o no (s/n): ").strip().lower()
            if ver == 's':
                todas = generar_palabras_distintas(palabra)
                print(f"\n {len(todas)} palabras distintas")
                print(" " + " ".join(todas))

    elif modo == "2":
        entrada_cantidades = input(" Cantidades separadas por espacio: ").strip()
        counts = [int(x.strip()) for x in entrada_cantidades.split()]
        resultado = multinomial(counts)
        n = sum(counts)
        print(f"\n n = {n} counts = {counts}")
        print(f" Resultado: {resultado}")

    else:
        print(" Opcion no valida")



#print("\n" + "█" * 60)
print(" CALCULADORA Palabras con letras repetidas")
#print("█" * 60)
print(" Modo 1: ingresa una palabra en mayusculas (ej: BANANA)")
print(" Modo 2: ingresa cantidades (ej: 4 3 2)")
modo_elegido = input("\n Elige modo 1 o 2: ").strip()

interfaz_multinomial(modo_elegido)

"""## <font face="Times New Roman"> Comentarios finales — Problema 1

En términos de desempeño, la solución resulta sumamente ágil al operar en tiempo lineal $O(n)$. La clave está en que utiliza un único ciclo para determinar el factorial general ($n!$) y otro para los factoriales individuales ($n_i!$). Una gran ventaja es que no requiere configuraciones adicionales para soportar números masivos.
Limitaciones: El código está acotado a palabras de hasta 8 caracteres si lo que se busca es listar físicamente cada palabra diferente. Ir más allá de ese límite ralentiza el proceso debido a la explosión factorial de las combinaciones. Por el contrario, si solo se requiere conocer la cifra final (el conteo matemático), el programa puede manejar prácticamente cualquier volumen.

---
# <font face="Times New Roman"> Problema 2: Distribución de Objetos en Cajas

## <font face="Times New Roman"> Descripción matemática

Se quiere contar el número de formas de distribuir $n$ objetos en $k$ cajas distinguibles.
El problema tiene varias variantes según las condiciones:

- Los **objetos** pueden ser idénticos (indistinguibles) o distintos (distinguibles).
- Las **cajas** pueden quedar vacías o no.
- Puede haber un **límite superior** $m$ de objetos por caja.

**Ejemplo:** ¿De cuántas formas se pueden repartir 10 dulces idénticos entre 3 niños
si cada niño puede recibir cualquier cantidad, incluyendo ninguno?

## <font face="Times New Roman"> Fórmulas usadas

**Caso 1 — Objetos idénticos, cajas vacías permitidas** ("estrellas y barras"):
$$\binom{n+k-1}{k-1}$$

**Caso 2 — Objetos idénticos, sin cajas vacías** (requiere $n \geq k$):
$$\binom{n-1}{k-1}$$

**Caso 3 — Objetos distintos, cajas vacías permitidas:**
$$k^n$$

**Caso 4 — Objetos distintos, sin cajas vacías** (número de sobreyecciones):
$$k! \cdot S(n,k)$$

donde $S(n,k)$ es el número de Stirling de segunda especie, que cuenta las formas de
partir $n$ elementos en $k$ subconjuntos no vacíos:
$$S(n,k) = k \cdot S(n-1,k) + S(n-1,k-1)$$

**Caso 5 — Con límite superior $m$ por caja** (inclusión-exclusión):

Para objetos idénticos ($x_i \leq m$, $\sum x_i = n$):
$$\sum_{j=0}^{k} (-1)^j \binom{k}{j} \binom{n - j(m+1) + k - 1}{k-1}$$

Para objetos distintos:
$$\sum_{j=0}^{k} (-1)^j \binom{k}{j} (k-j)^n$$

## <font face="Times New Roman"> Explicación del algoritmo

La función principal `distribuir(n, k, distintos, vacias, limite)` actúa como un **despachador**:
valida las entradas y redirige al cálculo correcto según los parámetros.

- `combinatoria(n, r)` usa `math.comb` de Python para calcular $\binom{n}{r}$ exactamente.
- `stirling2(n, k)` usa **programación dinámica** con la recurrencia $S(n,k) = k \cdot S(n-1,k) + S(n-1,k-1)$,
  evitando la explosión exponencial de la recursión directa. Complejidad: $O(n \cdot k)$ tiempo, $O(k)$ espacio.
- `inclusion_exclusion(n, k, m)` recorre los $k+1$ términos de la suma alternada. Complejidad: $O(k)$.

**Validaciones implementadas:**
- $n < 0$ o $k < 1$ → `ValueError`
- Cajas no vacías con $n < k$ → `ValueError` con mensaje explicativo
- Límite $m < 1$ → `ValueError`

## <font face="Times New Roman"> Código
"""

def combinatoria(n: int, r: int) -> int:
    "C(n, r) — coeficiente binomial exacto."
    if r < 0 or r > n:
        return 0
    return math.comb(n, r)


def stirling2(n: int, k: int) -> int:
    """
    Numero de Stirling de segunda especie S(n, k).
    Cuenta las formas de partir n elementos en k subconjuntos no vacios.
    S(n,k) = k*S(n-1,k) + S(n-1,k-1)
    """
    if n == 0 and k == 0:
        return 1
    if n == 0 or k == 0:
        return 0
    if k == 1 or k == n:
        return 1
    if k > n:
        return 0

    dp = [0] * (k + 1)
    dp[1] = 1
    for i in range(2, n + 1):
        for j in range(min(i, k), 0, -1):
            dp[j] = j * dp[j] + dp[j - 1]
    return dp[k]


def inclusion_exclusion(n: int, k: int, m: int, distintos: bool = False) -> int:
    """
    Cuenta distribuciones con limite superior m por caja.
    Usa el principio de inclusión-exclusión.
    """
    total = 0
    for j in range(k + 1):
        rem = n - j * (m + 1)
        if rem < 0:
            break
        signo = (-1) ** j
        if distintos:
            total += signo * combinatoria(k, j) * (k - j) ** n
        else:
            total += signo * combinatoria(k, j) * combinatoria(rem + k - 1, k - 1)
    return total


def distribuir(n: int, k: int,
               distintos: bool = False,
               vacias: bool = True,
               limite: int = None) -> int:
    """
    Cuenta las formas de distribuir n objetos en k cajas.

    Parametros:
      n        : número de objetos (>= 0)
      k        : número de cajas  (>= 1)
      distintos: True si los objetos son distinguibles
      vacias   : True si se permiten cajas vacías
      limite   : si se provee, límite superior de objetos por caja
    Retorna:
      numero de distribuciones (entero exacto)
    """
    #  validaciones
    if not isinstance(n, int) or n < 0:
        raise ValueError("n debe ser entero >= 0")
    if not isinstance(k, int) or k < 1:
        raise ValueError("k debe ser entero >= 1")
    if limite is not None and (not isinstance(limite, int) or limite < 1):
        raise ValueError("El límite debe ser entero >= 1")
    if not vacias and n < k:
        raise ValueError(
            f"Con cajas no vacías se necesita n >= k. "
            f"Recibido n={n}, k={k}."
        )

    # casos con límite superior por caja
    if limite is not None:
        return inclusion_exclusion(n, k, limite, distintos=distintos)

    # casos estandar
    if not distintos and vacias:
        return combinatoria(n + k - 1, k - 1)

    elif not distintos and not vacias:
        return combinatoria(n - 1, k - 1)

    elif distintos and vacias:
        return k ** n

    else:  # distintos y sin vacias
        S = stirling2(n, k)
        return math.factorial(k) * S

"""## <font face="Times New Roman"> Pruebas"""

def pruebas_distribucion():
    print("=" * 60)
    print("PRUEBAS — Problema 2: Distribucion de objetos en cajas")
    print("=" * 60)

    casos = [
        # (desc, n, k, distintos, vacias, limite, esperado)
        ("Idénticos, vacías OK:  n=10, k=3",    10, 3, False, True,  None, 66),
        ("Idénticos, sin vacías: n=5,  k=3",     5, 3, False, False, None, 6),
        ("Distintos, vacías OK:  n=3,  k=2",     3, 2, True,  True,  None, 8),
        ("Distintos, sin vacías: n=4,  k=2",     4, 2, True,  False, None, 14),
        ("Idénticos, límite m=4: n=9,  k=3",     9, 3, False, True,  4,    6),
        ("Distintos, límite m=2: n=4,  k=3",     4, 3, True,  True,  2,    18),
        ("Distintos, sin vacías: n=5,  k=3",     5, 3, True,  False, None, 150),
    ]

    aprobados = 0
    for desc, n, k, dist, vac, lim, esp in casos:
        try:
            r = distribuir(n, k, distintos=dist, vacias=vac, limite=lim)
            ok = r == esp
            if ok: aprobados += 1
            estado = " bien" if ok else "falla"
            print(f"  {estado}  {desc:42s} →  {r}  (esperado {esp})")
        except Exception as e:
            print(f"  error  {desc}: {e}")

    print(f"\n  Resultado: {aprobados}/{len(casos)} pruebas aprobadas\n")


pruebas_distribucion()

"""### <font face="Times New Roman"> Validación de casos especiales"""

def casos_especiales_distribucion():
    print("=" * 60)
    print("CASOS ESPECIALES — Problema 2")
    print("=" * 60)

    # Caso 1: n=0 objetos en k cajas
    r = distribuir(0, 5)
    print(f"  n=0 en k=5 cajas (idén, vacías OK)  : {r}  (esperado 1)")

    # Caso 2: n=k=1 sin vacías
    r = distribuir(1, 1, vacias=False)
    print(f"  n=1, k=1, sin vacías                 : {r}  (esperado 1)")

    # Caso 3: k=1 distintos, vacias OK
    r = distribuir(7, 1, distintos=True)
    print(f"  n=7, k=1, distintos, vacías OK       : {r}  (esperado 1)")

    # Caso 4: Stirling S(5,5) = 1
    s = stirling2(5, 5)
    print(f"  S(5,5)                               : {s}  (esperado 1)")

    # Caso 5: Stirling S(5,1) = 1
    s = stirling2(5, 1)
    print(f"  S(5,1)                               : {s}  (esperado 1)")

    # Caso 6: n < k sin vacías da error
    try:
        distribuir(2, 5, vacias=False)
    except ValueError as e:
        print(f"  n=2, k=5, sin vacías da error, bien")

    # Caso 7: k negativo da error
    try:
        distribuir(5, -1)
    except ValueError as e:
        print(f"  k=-1 :  error ")

    # Caso 8: numero grande exacto
    r = distribuir(20, 5, distintos=True, vacias=False)
    print(f"  n=20, k=5, distintos, sin vacías     : {r:,}")


casos_especiales_distribucion()

"""## <font face="Times New Roman"> Calculadora interactiva — Problema 2"""

def interfaz_distribucion():
    "Interfaz interactiva para usuario."
    print("\n============================================================")
    print("  CALCULADORA: Distribucion de objetos en cajas")
    print("============================================================")

    n = int(input("  Numero de objetos (n): "))
    k = int(input("  Numero de cajas    (k): "))

    print("  Tipo de objetos:")
    print("    1. Identicos")
    print("    2. Distintos")
    obj = input("  Opcion [1/2]: ").strip()
    distintos = (obj == "2")

    print("  Cajas vacias:")
    print("    1. Permitidas")
    print("    2. No permitidas")
    vac = input("  Opcion [1/2]: ").strip()
    vacias = (vac == "1")

    texto_limite = input("  Limite por caja (Enter para omitir): ").strip()
    limite = int(texto_limite) if texto_limite else None

    resultado = distribuir(n, k, distintos=distintos, vacias=vacias, limite=limite)

    tipo_obj = "distintos" if distintos else "identicos"
    tipo_caja = "con cajas vacias" if vacias else "sin cajas vacias"
    lim_str = f", limite={limite}" if limite else ""

    print(f"\n  Distribucion de {n} objetos {tipo_obj}")
    print(f"  en {k} cajas ({tipo_caja}{lim_str}):")
    print(f"\n  Resultado: {resultado:,}")


interfaz_distribucion()

"""## <font face="Times New Roman"> Comentarios finales — Problema 2

**Eficiencia:**

| Componente | Complejidad tiempo | Complejidad espacio |
|---|---|---|
| `combinatoria(n, r)` | $O(\min(r, n-r))$ | $O(1)$ |
| `stirling2(n, k)` | $O(n \cdot k)$ | $O(k)$ |
| `inclusion_exclusion` | $O(k)$ | $O(1)$ |

**Limitaciones:**
Para valores muy grandes de $n$ y $k$ con Stirling, el tiempo de cómputo puede crecer.
En la práctica, para $n, k \leq 1000$ el resultado es inmediato.

**Casos borde manejados:**
- $n = 0$: una sola distribución (todas las cajas vacías)
- $k = 1$: siempre hay exactamente 1 forma
- $n < k$ con cajas no vacías: imposible, se lanza `ValueError` con mensaje claro
- $k > n$ en Stirling: retorna 0 directamente sin entrar al ciclo

---
# <font face="Times New Roman"> Menú principal

Ejecuta la celda siguiente para iniciar la herramienta completa con ambos problemas.
"""

def ejecutar_opcion_menu(opcion):
    if opcion == "1":
        pruebas_multinomial()
        casos_especiales_multinomial()
        pruebas_distribucion()
        casos_especiales_distribucion()

    elif opcion == "2":
        # Acuerdate que ahora interfaz_multinomial necesita que le pasemos el modo
        print("\n Modo 1: ingresa una palabra en mayus (ej: BANANA)")
        print(" Modo 2: ingresa cantidades (ej: 4 3 2)")
        modo_elegido = input("\n Elija modo 1 o 2: ").strip()
        interfaz_multinomial(modo_elegido)

    elif opcion == "3":
        interfaz_distribucion()

    elif opcion == "4":
        print("chao")

    else:
        print(" opcion no valida, intente otra vez")


while True:
    #print("\n" + "─" * 60)
    print("  HERRAMIENTA DE CONTEO COMBINATORIO")
    #print("─" * 60)
    print("  1. Correr todas las pruebas automaticas")
    print("  2. Calculadora - Multinomial (letras repetidas)")
    print("  3. Calculadora - Distribucion de objetos en cajas")
    print("  4. Salir")

    opcion_usuario = input("\n  escoja opcion [1-4]: ").strip()

    ejecutar_opcion_menu(opcion_usuario)

    if opcion_usuario == "4":
        break